export const CATS = [
  { id: 'warz', label: 'Warzywa i owoce',      cls: 'c-warz' },
  { id: 'nab',  label: 'Nabiał i jajka',        cls: 'c-nab'  },
  { id: 'mies', label: 'Mięso i ryby',          cls: 'c-mies' },
  { id: 'piec', label: 'Pieczywo',              cls: 'c-piec' },
  { id: 'nap',  label: 'Napoje',                cls: 'c-nap'  },
  { id: 'chem', label: 'Chemia i kosmetyki',    cls: 'c-chem' },
  { id: 'mroz', label: 'Mrożonki',              cls: 'c-mroz' },
  { id: 'slod', label: 'Słodycze i przekąski',  cls: 'c-slod' },
  { id: 'syp',  label: 'Sypkie i konserwy',     cls: 'c-syp'  },
  { id: 'inne', label: 'Inne',                  cls: 'c-inne' },
];

export const STORES = [
  {
    id: 'lidl', label: 'Lidl',
    dot: '#0050AA',
    tileBgDark: '#0d1a30', tileFgDark: '#93c5fd', tileSubDark: '#4a7abf',
    tileBgLight: '#EBF3FF', tileFgLight: '#0C407A', tileSubLight: '#185FA5',
    logoBg: '#0050AA', logoFg: '#ffffff', logoAlt: '#FFCC00',
    logoLabel: 'Lidl',
    bg: '#EBF3FF', fg: '#0C407A',
  },
  {
    id: 'auchan', label: 'Auchan',
    dot: '#E30513',
    tileBgDark: '#1a0808', tileFgDark: '#fca5a5', tileSubDark: '#b84040',
    tileBgLight: '#FEE8E8', tileFgLight: '#8B0000', tileSubLight: '#B00000',
    logoBg: '#E30513', logoFg: '#ffffff', logoAlt: null,
    logoLabel: 'Auchan',
    bg: '#FEE8E8', fg: '#8B0000',
  },
  {
    id: 'biedronka', label: 'Biedronka',
    dot: '#CC0000',
    tileBgDark: '#1a0606', tileFgDark: '#fca5a5', tileSubDark: '#993333',
    tileBgLight: '#FFECEC', tileFgLight: '#7A0000', tileSubLight: '#990000',
    logoBg: '#CC0000', logoFg: '#ffffff', logoAlt: null,
    logoLabel: 'Bied.',
    bg: '#FFECEC', fg: '#7A0000',
  },
  {
    id: 'rossmann', label: 'Rossmann',
    dot: '#D4003B',
    tileBgDark: '#1a0610', tileFgDark: '#f9a8c4', tileSubDark: '#8a2044',
    tileBgLight: '#FFE8F0', tileFgLight: '#7A0020', tileSubLight: '#A0003B',
    logoBg: '#D4003B', logoFg: '#ffffff', logoAlt: null,
    logoLabel: 'Ross.',
    bg: '#FFE8F0', fg: '#7A0020',
  },
  {
    id: 'inny', label: 'Inne sklepy',
    dot: '#888780',
    tileBgDark: '#1e1e1e', tileFgDark: '#a0a09a', tileSubDark: '#5c5c58',
    tileBgLight: '#F1EFE8', tileFgLight: '#3a3a38', tileSubLight: '#5F5E5A',
    logoBg: '#3a3a3a', logoFg: '#a0a09a', logoAlt: null,
    logoLabel: null,
    bg: '#F1EFE8', fg: '#3a3a38',
  },
];

export const DICT = [
  ['Mleko','nab'],['Mleko 2%','nab'],['Mleko 3,2%','nab'],
  ['Jogurt naturalny','nab'],['Jogurt grecki','nab'],['Ser żółty','nab'],
  ['Ser gouda','nab'],['Ser edam','nab'],['Ser brie','nab'],
  ['Masło','nab'],['Masło extra','nab'],['Śmietana 18%','nab'],
  ['Śmietana 30%','nab'],['Śmietanka 30%','nab'],['Jajka','nab'],
  ['Jajka L','nab'],['Jajka M','nab'],['Twaróg','nab'],
  ['Twaróg półtłusty','nab'],['Kefir','nab'],['Maślanka','nab'],
  ['Ser feta','nab'],['Mozzarella','nab'],['Ricotta','nab'],
  ['Serek wiejski','nab'],['Serek homogenizowany','nab'],
  ['Pierś z kurczaka','mies'],['Udka z kurczaka','mies'],['Skrzydełka','mies'],
  ['Mięso mielone','mies'],['Mięso mielone wieprzowe','mies'],['Schab','mies'],
  ['Karkówka','mies'],['Boczek','mies'],['Szynka','mies'],
  ['Szynka gotowana','mies'],['Polędwica','mies'],['Kiełbasa','mies'],
  ['Kiełbasa śląska','mies'],['Parówki','mies'],['Kabanosy','mies'],
  ['Łosoś','mies'],['Łosoś wędzony','mies'],['Dorsz','mies'],
  ['Tuńczyk w puszce','mies'],['Sardynki','mies'],['Krewetki','mies'],
  ['Pstrąg','mies'],['Mintaj','mies'],['Makrela wędzona','mies'],
  ['Chleb','piec'],['Chleb żytni','piec'],['Chleb razowy','piec'],
  ['Chleb pszenny','piec'],['Chleb tostowy','piec'],['Bułki','piec'],
  ['Bułka kajzerka','piec'],['Bagietka','piec'],['Rogaliki','piec'],
  ['Croissant','piec'],['Tortilla','piec'],['Pita','piec'],
  ['Jabłka','warz'],['Banany','warz'],['Pomidory','warz'],
  ['Pomidory koktajlowe','warz'],['Ogórki','warz'],['Ogórek szklarniowy','warz'],
  ['Marchew','warz'],['Ziemniaki','warz'],['Cebula','warz'],
  ['Czosnek','warz'],['Sałata','warz'],['Roszponka','warz'],
  ['Papryka','warz'],['Papryka czerwona','warz'],['Brokuły','warz'],
  ['Szpinak','warz'],['Pomarańcze','warz'],['Cytryny','warz'],
  ['Winogrona','warz'],['Truskawki','warz'],['Gruszki','warz'],
  ['Maliny','warz'],['Borówki','warz'],['Awokado','warz'],
  ['Kapusta biała','warz'],['Kapusta czerwona','warz'],['Por','warz'],
  ['Rzodkiewki','warz'],['Pieczarki','warz'],['Kalafior','warz'],
  ['Kukurydza','warz'],['Groszek','warz'],['Szczypiorek','warz'],
  ['Batat','warz'],['Cukinia','warz'],['Bakłażan','warz'],
  ['Woda mineralna','nap'],['Woda gazowana','nap'],['Woda niegazowana','nap'],
  ['Sok pomarańczowy','nap'],['Sok jabłkowy','nap'],['Sok multiwitamina','nap'],
  ['Cola','nap'],['Pepsi','nap'],['Sprite','nap'],
  ['Fanta','nap'],['Piwo','nap'],['Wino białe','nap'],
  ['Wino czerwone','nap'],['Herbata','nap'],['Herbata zielona','nap'],
  ['Kawa mielona','nap'],['Kawa ziarnista','nap'],['Kawa rozpuszczalna','nap'],
  ['Kakao','nap'],['Napój energetyczny','nap'],
  ['Proszek do prania','chem'],['Kapsułki do prania','chem'],['Płyn do naczyń','chem'],
  ['Tabletki do zmywarki','chem'],['Papier toaletowy','chem'],['Ręczniki papierowe','chem'],
  ['Szampon','chem'],['Odżywka do włosów','chem'],['Pasta do zębów','chem'],
  ['Szczoteczka do zębów','chem'],['Mydło','chem'],['Żel pod prysznic','chem'],
  ['Dezodorant','chem'],['Płyn do podłóg','chem'],['Mleczko do łazienki','chem'],
  ['Ściereczki','chem'],['Worki na śmieci','chem'],['Folia aluminiowa','chem'],
  ['Papier do pieczenia','chem'],['Woreczki strunowe','chem'],
  ['Lody','mroz'],['Lody waniliowe','mroz'],['Pizza mrożona','mroz'],
  ['Warzywa mrożone','mroz'],['Szpinak mrożony','mroz'],['Brokuły mrożone','mroz'],
  ['Frytki mrożone','mroz'],['Pierogi mrożone','mroz'],['Kopytka mrożone','mroz'],
  ['Filet rybny mrożony','mroz'],['Ośmiorniczki mrożone','mroz'],
  ['Czekolada','slod'],['Czekolada mleczna','slod'],['Czekolada gorzka','slod'],
  ['Ciastka','slod'],['Herbatniki','slod'],['Chipsy','slod'],
  ['Chipsy paprykowe','slod'],['Żelki','slod'],['Żelki owocowe','slod'],
  ['Baton','slod'],['Kit Kat','slod'],['Snickers','slod'],
  ['Paluszki','slod'],['Precle','slod'],['Popcorn','slod'],
  ['Batoniki owsiane','slod'],['Wafelki','slod'],['Pierniczki','slod'],
  ['Ryż','syp'],['Ryż jaśminowy','syp'],['Makaron','syp'],
  ['Makaron spaghetti','syp'],['Makaron penne','syp'],['Makaron tagliatelle','syp'],
  ['Mąka pszenna','syp'],['Mąka razowa','syp'],['Cukier','syp'],
  ['Cukier puder','syp'],['Sól','syp'],['Sól morska','syp'],
  ['Kasza gryczana','syp'],['Kasza jaglana','syp'],['Kasza bulgur','syp'],
  ['Płatki owsiane','syp'],['Musli','syp'],['Olej słonecznikowy','syp'],
  ['Olej rzepakowy','syp'],['Oliwa z oliwek','syp'],['Ocet','syp'],
  ['Ocet jabłkowy','syp'],['Sos sojowy','syp'],['Koncentrat pomidorowy','syp'],
  ['Konserwa pomidorowa','syp'],['Groszek konserwowy','syp'],['Kukurydza konserwowa','syp'],
  ['Fasola biała','syp'],['Soczewica czerwona','syp'],['Ciecierzyca','syp'],
  ['Bulion w kostkach','syp'],['Majonez','syp'],['Musztarda','syp'],
  ['Ketchup','syp'],['Dżem','syp'],['Miód','syp'],
  ['Nutella','syp'],['Masło orzechowe','syp'],
];

export const KEYWORD_RULES = [
  { kws: ['mleko','jogurt','śmietan','jajk','masł','kefir','maślank','feta','mozza','ricott','serek','twaróg','ser '], cat: 'nab' },
  { kws: ['kurczak','wołow','wieprzow','mięs','boczek','szynk','kiełbas','parówk','kabanos','łosoś','dorsz','tuńczyk','sardynk','krewetk','pstrąg','mintaj','makrela','filet ryb','indyk','karkówk','schab','polędwic'], cat: 'mies' },
  { kws: ['chleb','bułk','bagiet','tost','rogalik','croissant','tortilla','pita','pieczywo'], cat: 'piec' },
  { kws: ['jabłk','banan','pomidor','ogórek','marchew','ziemniak','cebul','czosnek','sałat','papryka','brokuł','szpinak','pomarańcz','cytryn','winogron','truskawk','gruszk','maliny','borówk','awokado','kapust','rzodkiewk','pieczark','kalafior','kukurydz','groszek','szczypior','batat','cukini','bakłażan','por '], cat: 'warz' },
  { kws: ['woda','sok','cola','pepsi','sprite','fanta','piwo','wino','herbata','kawa','kakao','napój energet'], cat: 'nap' },
  { kws: ['proszek do prania','kapsułk','płyn do naczyń','tabletk do zmyw','papier toalet','ręcznik papier','szampon','odżywka','pasta do zębów','szczoteczk','mydło','żel pod','dezodor','płyn do podłóg','mleczko do łazienki','ściereczk','worki na śmieci','folia aluminiow','papier do piecz','woreczki struno'], cat: 'chem' },
  { kws: ['mrożon','mrożone','lody','pizza mroż','frytki','pierogi mroż','kopytka mroż'], cat: 'mroz' },
  { kws: ['czekolad','ciastk','herbatnik','chipsy','żelki','baton','kit kat','snickers','paluszk','precle','popcorn','wafelk','pierniczk'], cat: 'slod' },
  { kws: ['ryż','makaron','mąka','cukier',' sól ','sól ','kasza','płatki','musli','olej','oliwa','ocet','sos sojowy','koncentrat','konserw','fasola','soczewic','ciecierzyc','bulion','majonez','musztard','ketchup','dżem','miód','nutella','masło orzech'], cat: 'syp' },
];
